With Borrowers_CTE as(
	SELECT first_name , last_name from BORROWERS inner join LOANS 
	on  BORROWERS.BORROWERID = LOANS.BORROWERID 
	Where LOANS.DATE_RETURNED  < GETDATE() GROUP BY BORROWERS.BORROWERID , BORROWERS.FIRST_NAME , BORROWERS.LAST_NAME Having COUNT(*) >= 2
) Select * From  Borrowers_CTE
