CREATE TABLE BOOKS(
	BOOKID INT NOT NULL PRIMARY KEY,
	TITLE VARCHAR(100) ,
	AUTHOR VARCHAR(60),
	ISBN VARCHAR(20),
	PUBLISHED_DATE DATE,
	GENRE VARCHAR(20),
	SHELF_LOCATION VARCHAR(5),
	CURRENT_STATUS VARCHAR(1)
);

CREATE TABLE BORROWERS(
	BORROWERID INT NOT NULL PRIMARY KEY,
	FIRST_NAME VARCHAR(20),
	LAST_NAME VARCHAR(20),
	EMAIL VARCHAR(30),
	DATE_OF_BIRTH DATE,
	MEMPERSHIP_DATE DATE,
);

CREATE TABLE LOANS(
	LOANID INT NOT NULL PRIMARY KEY,
	BOOKID INT NOT NULL FOREIGN KEY REFERENCES BOOKS(BOOKID),
	BORROWERID INT NOT NULL FOREIGN KEY REFERENCES BORROWERS(BORROWERID),
	DATE_BORROWED DATE,
	DUE_DATE DATE,
	DATE_RETURNED DATE NULL,
);
